<?php

use yii\db\Schema;
use yii\db\Migration;

class m141123_104056_create_card_set_table extends Migration
{
    public function safeUp()
    {
        $this->createTable('card_set', [
            'card_set_id' => Schema::TYPE_STRING . ' NOT NULL',
            'name' => Schema::TYPE_STRING . ' NOT NULL',
            'date' => Schema::TYPE_DATE . ' NOT NULL',
            'created_at' => Schema::TYPE_TIMESTAMP,
            'updated_at' => Schema::TYPE_TIMESTAMP
        ]);
        $this->addPrimaryKey('pk_card_set', 'card_set', 'card_set_id');

        $sets = [
            ['Born of the Gods', 'BNG', '2014-02-01', gmdate('Y-m-d H:i:s')],
            ['Journey into Nyx', 'JOU', '2014-05-01', gmdate('Y-m-d H:i:s')],
            ['Khans of Tarkir', 'KTK', '2014-09-01', gmdate('Y-m-d H:i:s')],
            ['Magic 2015 Core Set', 'M15', '2014-07-01', gmdate('Y-m-d H:i:s')],
            ['Theros', 'THS', '2013-09-01', gmdate('Y-m-d H:i:s')]
        ];

        $this->batchInsert('card_set', ['name', 'card_set_id', 'date', 'created_at'], $sets);

        parent::safeUp(); // TODO: Change the autogenerated stub
    }

    public function safeDown()
    {
        $this->dropTable('card_set');
        parent::safeDown(); // TODO: Change the autogenerated stub
    }
}
